runtime: nodejs14
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: "301"
  - url: .*
    script: auto
env_variables:
  NODE_ENV: production
  DIALOGFLOW_ENVIRONNEMENT: {DIALOGFLOW_ENVIRONNEMENT}
  PROJECT_ID: {PROJECT_ID}
  FEEDBACK_TOPIC_NAME: {FEEDBACK_TOPIC_NAME}
  BOT_NAME: {BOT_NAME}
  USER_INFO_ENV: {USER_INFO_ENV}
  USER_INFO_URL_DOMAIN: {USER_INFO_URL_DOMAIN}
  USER_INFO_URL_PATH: {USER_INFO_URL_PATH}
  FETCHER_IMAGE_FUNCTION_URL: {FETCHER_IMAGE_FUNCTION_URL}

automatic_scaling:
  min_idle_instances: {MIN_IDLE_INSTANCES}
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
